# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: utterance_segmentation/rpc/utterance_segmentation.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='utterance_segmentation/rpc/utterance_segmentation.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n7utterance_segmentation/rpc/utterance_segmentation.proto\"E\n\tUSRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x16\n\x0esegmenter_type\x18\x02 \x01(\t\x12\x12\n\nparse_ssml\x18\x03 \x01(\x08\"\x1a\n\nUSResponse\x12\x0c\n\x04text\x18\x01 \x03(\t2:\n\x16utterance_segmentation\x12 \n\x05\x63hunk\x12\n.USRequest\x1a\x0b.USResponseb\x06proto3'
)




_USREQUEST = _descriptor.Descriptor(
  name='USRequest',
  full_name='USRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='USRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='segmenter_type', full_name='USRequest.segmenter_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='parse_ssml', full_name='USRequest.parse_ssml', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=128,
)


_USRESPONSE = _descriptor.Descriptor(
  name='USResponse',
  full_name='USResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='USResponse.text', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['USRequest'] = _USREQUEST
DESCRIPTOR.message_types_by_name['USResponse'] = _USRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

USRequest = _reflection.GeneratedProtocolMessageType('USRequest', (_message.Message,), {
  'DESCRIPTOR' : _USREQUEST,
  '__module__' : 'utterance_segmentation.rpc.utterance_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:USRequest)
  })
_sym_db.RegisterMessage(USRequest)

USResponse = _reflection.GeneratedProtocolMessageType('USResponse', (_message.Message,), {
  'DESCRIPTOR' : _USRESPONSE,
  '__module__' : 'utterance_segmentation.rpc.utterance_segmentation_pb2'
  # @@protoc_insertion_point(class_scope:USResponse)
  })
_sym_db.RegisterMessage(USResponse)



_UTTERANCE_SEGMENTATION = _descriptor.ServiceDescriptor(
  name='utterance_segmentation',
  full_name='utterance_segmentation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=158,
  serialized_end=216,
  methods=[
  _descriptor.MethodDescriptor(
    name='chunk',
    full_name='utterance_segmentation.chunk',
    index=0,
    containing_service=None,
    input_type=_USREQUEST,
    output_type=_USRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UTTERANCE_SEGMENTATION)

DESCRIPTOR.services_by_name['utterance_segmentation'] = _UTTERANCE_SEGMENTATION

# @@protoc_insertion_point(module_scope)
