# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from utterance_segmentation.rpc import utterance_segmentation_pb2 as utterance__segmentation_dot_rpc_dot_utterance__segmentation__pb2


class utterance_segmentationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.chunk = channel.unary_unary(
                '/utterance_segmentation/chunk',
                request_serializer=utterance__segmentation_dot_rpc_dot_utterance__segmentation__pb2.USRequest.SerializeToString,
                response_deserializer=utterance__segmentation_dot_rpc_dot_utterance__segmentation__pb2.USResponse.FromString,
                )


class utterance_segmentationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def chunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_utterance_segmentationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'chunk': grpc.unary_unary_rpc_method_handler(
                    servicer.chunk,
                    request_deserializer=utterance__segmentation_dot_rpc_dot_utterance__segmentation__pb2.USRequest.FromString,
                    response_serializer=utterance__segmentation_dot_rpc_dot_utterance__segmentation__pb2.USResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'utterance_segmentation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class utterance_segmentation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def chunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/utterance_segmentation/chunk',
            utterance__segmentation_dot_rpc_dot_utterance__segmentation__pb2.USRequest.SerializeToString,
            utterance__segmentation_dot_rpc_dot_utterance__segmentation__pb2.USResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
